# Generated by Django 6.1.1 on 2026-09-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='duration',
            field=models.CharField(choices=[('FULL_DAY', 'Full Day'), ('AM', 'AM'), ('PM', 'PM')], default='FULL_DAY', max_length=20),
        ),
    ]
