# Generated by Django 6.0.6 on 2026-09-09 15:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payslip',
            options={'ordering': ['-week_start'], 'verbose_name': 'Weekly Payslip', 'verbose_name_plural': 'Weekly Payslips'},
        ),
        migrations.RenameField(
            model_name='payslip',
            old_name='pay_period_start',
            new_name='week_end',
        ),
        migrations.RenameField(
            model_name='payslip',
            old_name='pay_period_end',
            new_name='week_start',
        ),
        migrations.AddField(
            model_name='payslip',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='payslip',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='payslip',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='payslip',
            name='overtime_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
    ]
