# Generated by Django 6.0.6 on 2026-09-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', 'employee__first_name', 'employee__last_name'], 'verbose_name': 'Attendance Record', 'verbose_name_plural': 'Attendance Records'},
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='check_in_time',
            new_name='clock_in',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='check_out_time',
            new_name='clock_out',
        ),
        migrations.AddField(
            model_name='attendance',
            name='break_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('SICK', 'Sick'), ('HOLIDAY', 'Holiday')], default='PRESENT', max_length=20),
        ),
    ]
